---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

# nfldatadashboard

## Goal

Interactively compare NFL player's performance within positions. Only QB, WR, TE, and RB from Next Gen Stats 2023 season using {nflreadr}.

## Target Outcomes

1.  ~~Select and compare player performance within positions~~
2.  ~~Visualize the distribution of player performance within positions~~
3.  List custom player ranking within positions

## Questions

1.  ~~How does my select player compare to other players within and across position's performance statistics?~~
2.  ~~How do players perform overall across performance statistics?~~
3.  What are player's overall performance for select statistics?

## Design

-   4 navbar tabs for each position
    -   Sidebar: Position statistics selection and descriptions - will be passed to plots below
    -   Select tab
        -   Players selection
        -   Season-average heatmap
        -   Season-wide boxplots - interactive
    -   Explore tab
        -   Players selection
        -   Season-wide scatterplot - interactive
        -   Season-average vs. variance scatterplot - interactive

## Data

```{r,echo=FALSE,include=FALSE}
devtools::load_all()
data_obj <- data_object$new()
```

[Two types of player statistics:]{.underline}

1.  Season-wide (each week)
2.  Season-average (average over weeks)

[Three positions:]{.underline}

1.  Quarterback (QB)
2.  Wide receiver (WR)
3.  Tight End (TE)
4.  Running back (RB)


[Performance statistics:]{.underline}

1.  QB: `r length(data_obj$get_position_vars('qb'))`
2.  WR: `r length(data_obj$get_position_vars('wr'))`
3.  TE: `r length(data_obj$get_position_vars('te'))`
4.  RB: `r length(data_obj$get_position_vars('rb'))`
